### ISSUE TITLE
 how to use it

### ISSUE THREAD

**Issue by CaryQY** [alltom/dirgui#1]
hi,

i use remmina and write vnc address 127.0.0.1:5900. but it stick in "reading challenge response…"

**Comment by anotherjesse** [comment]
I had the same issue with both tightvnc and the built-in macos vnc viewer (10.15.7).

I was able to get to get passed it by commenting out the line:

		log.Print("reading challenge response…")
		if _, err := io.ReadFull(conn, buf[:16]); err != nil {
			// return fmt.Errorf("couldn't read challenge response: %v", err)
		}

**Comment by alltom** [comment]
FWIW, I see a bug that might be causing this. main.go advertises "RFB 003.008" but then uses the 3.3 code path below (old = true). It happens to work because the VNC client I use always requests RFB 3.3 anyway, but it's probable that y'all are just using clients that accept the offer of 3.8.

To fix it for your uses, you could try setting old = false, so it takes the 3.8 authentication path. The better change is to use the appropriate path based on what version the client requests.

**Comment by alltom** [comment]
I'm about to disable Issues on this repo, but I'll leave pull requests open. Feel free to contact me on Twitter (alltom) or via e-mail (tom@alltom.com).

**Comment by alltom** [comment]
(Actually, I am going to enable Discussions on this repo too.)
